# If you see an error tell me in spigot or bukkit!

#####################################
#+---------------------------------+#
#|            CONFIGS              |#
#+---------------------------------+#
#####################################

# Enable or disable chicken
disable-chicken: false

damage:
   block: true
#   player: true (soon)
#   other-entity: true (soon)




#####################################
#+---------------------------------+#
#|            MESSAGES             |#
#+---------------------------------+#
#####################################

messages:
   enable: true
   throw: "&aYou throw an egg!"

